### ISSUE TITLE
I get issue when get

### ISSUE THREAD

**Issue by hendras1722** [philnash/react-express-starter#23]
I'm success get api status 200 but response "you need to enable JavaScript to run this app"
when development not problem. but when production build react i got response this.

pls help me. thanks you
![image](https://user-images.githubusercontent.com/57746184/130328408-f146cd76-2187-4869-8c85-4fccce265256.png)

**Comment by philnash** [comment]
How are you running this in production?

**Comment by hendras1722** [comment]
npm run build. then serve -s build.

**Comment by philnash** [comment]
Right, so this project has both an Express server and a React project. If you just build the React project and serve it, then it doesn't have the greeting endpoint any more.

I think you're seeing the message in the preview in dev tools because dev tools doesn't run JS for the preview. But also because you are loading the React application when you hit the greeting endpoint instead of the server endpoint.

**Comment by hendras1722** [comment]
Do you have solution ?

**Comment by philnash** [comment]
So, if you want to run the application in production with the existing Node.js server, then it needs a couple of updates to get it running. Please note that the server is very bare bones, so you may want to do more with it, but this is a good starting point.

Update `server/index.js` to this:

```js
const express = require("express");
const bodyParser = require("body-parser");
const pino = require("express-pino-logger")();
const path = require("path");

const app = express();
app.use(bodyParser.urlencoded({ extended: false }));
app.use(pino);

app.get("/api/greeting", (req, res) => {
  const name = req.query.name || "World";
  res.setHeader("Content-Type", "application/json");
  res.send(JSON.stringify({ greeting: `Hello ${name}!` }));
});

app.use(express.static(path.join(__dirname, "..", "build")));

app.get("/", function (req, res) {
  res.sendFile(path.join(__dirname, "..", "build", "index.html"));
});

app.listen(3001, () =>
  console.log("Express server is running on localhost:3001")
);
```

In this, we have added static file serving so that the Express server serves the static assets from the `build` directory.

Then, build the client side application:

```
npm run build
``` 

Finally, start the server:

```
node server/index.js
```

The server will be running on http://localhost:3001.

Let me know how you get on with that.

**Comment by hendras1722** [comment]
wow. great thank you. work. but when browser refresh display this. 
![image](https://user-images.githubusercontent.com/57746184/130389964-ddcedd95-c51f-4ecc-bbc8-67abd4b959d8.png)

**Comment by hendras1722** [comment]
![image](https://user-images.githubusercontent.com/57746184/130390148-ca023c85-ec36-4bc7-9a37-65b0593e052f.png)

done I add script /login that's work. thank you sir

**Comment by philnash** [comment]
Glad it's working for you now!
